<a href="https://colab.research.google.com/github/npenaq/MetNumUN2023I/blob/main/Quiz1/npenaq_Quiz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version
import numpy as np

print('NumPy', np.__version__)

Python 3.8.10
NumPy 1.22.4


This quiz was created originaly in:

- Python 3.6.9

- NumPy: 1.19.5

## **1. *FizzBuzz*  - Python**

**Solution**

In [1]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzz(x):
      answer =""
      if x % 3 == 0 and x % 5 == 0:
            answer='FizzBuzz!'
      elif x % 3 == 0 :
            answer ='Fizz!'
      elif x % 5 == 0:
            answer ='Buzz!'
      else: 
        answer= '...'
      return answer


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>


In [2]:
print(FizzBuzz(3))
print(FizzBuzz(7))
print(FizzBuzz(5))
print(FizzBuzz(11))
print(FizzBuzz(15))

Fizz!
...
Buzz!
...
FizzBuzz!


## **2. *FizzBuzzList*  - Python**
---

Write the function *FizzBuzzList* that returns a list with the answers of *FizzBuzz* for the integer numbers $1$ to $n$ (including $n$).

**Sample testcases**

```python
#run this sample testcases to help you validate your solution

FizzBuzzList(4)
#  --> Expected output: ['...', '...', 'Fizz!', '...']
 
FizzBuzzList(-1)
#  --> Expected output: []
```
---

**Solution**

In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzzList(n):
    ans = []
    if  n<0:
      return ans
    for x in range (1,n+1):
          if x % 3 == 0 and x % 5 == 0:
            answer='FizzBuzz!'
          elif x % 3 == 0 :
            answer ='Fizz!'
          elif x % 5 == 0:
            answer ='Buzz!'
          else:
            answer= '...'
          ans.append(answer)
    return ans

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>

In [ ]:
print(FizzBuzzList(5))
print(FizzBuzzList(-30))

['...', '...', 'Fizz', '...', 'Buzz']
[]


Expected output:
``` 
['...', '...', 'Fizz!', '...', 'Buzz!']
[]
```

## **3. *Standarize* - z scores - NumPy**

**Solution**

In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def standarize(X):
  X_standarized = (X-np.mean(X))/np.std(X)
  return X_standarized
X0 = np.array([4.8, 4.0, 4.2, 4.0, 5.0])
standarize(X0)


array([ 0.95346259, -0.95346259, -0.47673129, -0.95346259,  1.43019388])

In [ ]:
X1 = np.arange(5)
standarize(X1)

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

## **4. *Main diagonal matrix*  - NumPy**

**IMPORTANT:** Solve this exercise using the ***`NumPy`*** function ***`diag`***  and ***`astype`*** not using prograrmming structures like ***`if`*** or ***`for`***.

In [ ]:
import numpy as np
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]
    
])

print(A.astype(float))

print(np.diag(A))

print(np.diag(np.diag(A)))

[[1. 0. 2. 9. 2.]
 [9. 2. 6. 5. 7.]
 [6. 4. 3. 4. 7.]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


---

###**Problem Description**

**Task:** Given a numpy matrix $A$ (2-D array) return the diagonal matrix with the elements of its main diagonal.
 

**Input Format:** The input consists of a numpy matrix $A$ (2-D array).

**Output Format:**  The diagonal matrix with the elemnts of its main diagonal.

In [ ]:
import numpy as np

def main_diagonal_matrix(A):
  D = np.diag(np.diag(A).astype(float))
  return D
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]

])
main_diagonal_matrix(A)


array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [ ]:

B = np.array([
    [4, 0, 2],
    [9, 5, 6],
    [1, 9, 6],
    [3, 0, 5]

])
main_diagonal_matrix(B)


array([[4., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.]])